Repository sparta-newsfeed-project/newsfeed, pull requests merged in 2025-02, with the labels that each got.

#2 프로젝트 초기 설정 및 공통 모듈 구성
  newsfeed.sql
  src/main/java/com/example/newsfeed/NewsfeedApplication.java
  src/main/java/com/example/newsfeed/comment/domain/Comment.java
  src/main/java/com/example/newsfeed/comment/repository/CommentRepository.java
  src/main/java/com/example/newsfeed/exception/CustomException.java
  src/main/java/com/example/newsfeed/exception/ErrorResponse.java
  src/main/java/com/example/newsfeed/exception/ExceptionType.java
  src/main/java/com/example/newsfeed/exception/GlobalExceptionHandler.java
  src/main/java/com/example/newsfeed/follow/domain/Follow.java
  src/main/java/com/example/newsfeed/follow/repository/FollowRepository.java
  src/main/java/com/example/newsfeed/global/BaseTimeEntity.java
  src/main/java/com/example/newsfeed/post/domain/Post.java
  src/main/java/com/example/newsfeed/post/repository/PostRepository.java
  src/main/java/com/example/newsfeed/user/domain/User.java
  src/main/java/com/example/newsfeed/user/repository/UserRepository.java
  src/main/resources/application.properties
Labels: 기능

#7 feat: 회원가입 API 개발 (#4)
  build.gradle
  src/main/java/com/example/newsfeed/user/config/PasswordEncoder.java
  src/main/java/com/example/newsfeed/user/controller/AuthController.java
  src/main/java/com/example/newsfeed/user/dto/AuthRequestDto.java
  src/main/java/com/example/newsfeed/user/repository/UserRepository.java
  src/main/java/com/example/newsfeed/user/service/AuthService.java
Labels: 기능

#9 feat: 댓글 작성 API 구현
  src/main/java/com/example/newsfeed/comment/controller/CommentController.java
  src/main/java/com/example/newsfeed/comment/dto/CommentRequestDto.java
  src/main/java/com/example/newsfeed/comment/dto/CommentResponseDto.java
  src/main/java/com/example/newsfeed/comment/service/CommentService.java
Labels: 기능

#11 인증 로직 구현
  src/main/java/com/example/newsfeed/auth/argument/Authenticated.java
  src/main/java/com/example/newsfeed/auth/argument/AuthenticatedArgumentResolver.java
  src/main/java/com/example/newsfeed/auth/config/PasswordEncoder.java
  src/main/java/com/example/newsfeed/auth/config/SecurityConfig.java
  src/main/java/com/example/newsfeed/auth/config/WebConfig.java
  src/main/java/com/example/newsfeed/auth/consts/SessionConst.java
  src/main/java/com/example/newsfeed/auth/controller/AuthController.java
  src/main/java/com/example/newsfeed/auth/dto/AuthRequestDto.java
  src/main/java/com/example/newsfeed/auth/dto/AuthResponseDto.java
  src/main/java/com/example/newsfeed/auth/filter/LoginFilter.java
  src/main/java/com/example/newsfeed/auth/service/AuthService.java
  src/main/java/com/example/newsfeed/exception/ExceptionType.java
  src/main/java/com/example/newsfeed/user/controller/AuthController.java
  src/main/java/com/example/newsfeed/user/repository/UserRepository.java
  src/main/java/com/example/newsfeed/user/service/AuthService.java
Labels: 기능

#16 feat: 회원탈퇴 API 구현 (#14)
  src/main/java/com/example/newsfeed/exception/ExceptionType.java
  src/main/java/com/example/newsfeed/global/BaseTimeEntity.java
  src/main/java/com/example/newsfeed/user/controller/UserController.java
  src/main/java/com/example/newsfeed/user/dto/UserRequestDto.java
  src/main/java/com/example/newsfeed/user/repository/UserRepository.java
  src/main/java/com/example/newsfeed/user/service/UserService.java
Labels: 기능

#22 Follow 생성/삭제 기능 구현
  newsfeed.sql
  src/main/java/com/example/newsfeed/exception/ExceptionType.java
  src/main/java/com/example/newsfeed/follow/controller/FollowController.java
  src/main/java/com/example/newsfeed/follow/domain/Follow.java
  src/main/java/com/example/newsfeed/follow/repository/FollowRepository.java
  src/main/java/com/example/newsfeed/follow/service/FollowService.java
  src/main/java/com/example/newsfeed/user/service/UserService.java
Labels: 기능

#24 feat: 팔로워/팔로잉 조회 구현
  src/main/java/com/example/newsfeed/follow/controller/FollowController.java
  src/main/java/com/example/newsfeed/follow/dto/FollowListResponse.java
  src/main/java/com/example/newsfeed/follow/repository/FollowRepository.java
  src/main/java/com/example/newsfeed/follow/service/FollowService.java
Labels: 기능

#25 사용자 soft delete를 어노테이션을 이용하도록 변경
  src/main/java/com/example/newsfeed/auth/service/AuthService.java
  src/main/java/com/example/newsfeed/exception/ExceptionType.java
  src/main/java/com/example/newsfeed/global/BaseTimeEntity.java
  src/main/java/com/example/newsfeed/user/domain/User.java
  src/main/java/com/example/newsfeed/user/repository/UserRepository.java
  src/main/java/com/example/newsfeed/user/service/UserService.java
Labels: 리팩토링

#33 댓글 페이지네이션 조회 에러 해결
  src/main/java/com/example/newsfeed/comment/controller/CommentController.java
  src/main/java/com/example/newsfeed/comment/dto/CommentResponseDto.java
  src/main/java/com/example/newsfeed/comment/repository/CommentRepository.java
  src/main/java/com/example/newsfeed/comment/service/CommentService.java
  src/main/java/com/example/newsfeed/user/repository/UserRepository.java
Labels: 오류, 해결

#34 Pagination 공통 응답 객체 구현
  src/main/java/com/example/newsfeed/global/pagination/PaginationResponse.java
Labels: 기능

#35 Follow API 구조 정리 / 리팩토링
  src/main/java/com/example/newsfeed/follow/controller/FollowController.java
  src/main/java/com/example/newsfeed/follow/service/FollowService.java
Labels: 리팩토링

#39 Post CRUD 기본 구현
  src/main/java/com/example/newsfeed/post/controller/PostController.java
  src/main/java/com/example/newsfeed/post/dto/PostRequest.java
  src/main/java/com/example/newsfeed/post/dto/PostResponse.java
  src/main/java/com/example/newsfeed/post/service/PostService.java
Labels: 기능

#40 사용자 팔로잉 게시글 조회 구현
  src/main/java/com/example/newsfeed/post/controller/PostController.java
  src/main/java/com/example/newsfeed/post/repository/PostRepository.java
  src/main/java/com/example/newsfeed/post/service/PostService.java
Labels: 기능

#46 사용자 작성 게시글 조회 구현
  src/main/java/com/example/newsfeed/post/controller/PostController.java
  src/main/java/com/example/newsfeed/post/repository/PostRepository.java
  src/main/java/com/example/newsfeed/post/service/PostService.java
Labels: 기능, 수정

#47 회원 탈퇴 시 사용자 관련 데이터도 함께 삭제하도록 수정
  src/main/java/com/example/newsfeed/comment/repository/CommentRepository.java
  src/main/java/com/example/newsfeed/follow/repository/FollowRepository.java
  src/main/java/com/example/newsfeed/post/repository/PostRepository.java
  src/main/java/com/example/newsfeed/user/domain/User.java
  src/main/java/com/example/newsfeed/user/service/UserService.java
Labels: 수정

#48 게시글 조회 시 댓글 수 정보 추가 구현
  newsfeed.sql
  src/main/java/com/example/newsfeed/post/domain/Post.java
  src/main/java/com/example/newsfeed/post/dto/PostResponse.java
Labels: 기능

#49 rename: commentCount 업데이트 메서드 이름 변경
  src/main/java/com/example/newsfeed/post/domain/Post.java
Labels: 리팩토링

#54 Follow 조회 시 soft delete 제외 적용
  src/main/java/com/example/newsfeed/follow/domain/Follow.java
Labels: 기능, 수정

#55 사용자 프로필 조회시 팔로잉/팔로워 수 정보 추가
  src/main/java/com/example/newsfeed/follow/repository/FollowRepository.java
  src/main/java/com/example/newsfeed/user/controller/UserController.java
  src/main/java/com/example/newsfeed/user/dto/UserResponseDto.java
  src/main/java/com/example/newsfeed/user/service/UserService.java
Labels: 기능, 수정

#62 Follow 기능 관련 리팩토링
  src/main/java/com/example/newsfeed/follow/controller/FollowController.java
  src/main/java/com/example/newsfeed/follow/service/FollowService.java
  src/main/java/com/example/newsfeed/post/repository/PostRepository.java
  src/main/java/com/example/newsfeed/post/service/PostService.java
Labels: 리팩토링

#65 사용자 프로필 수정 시 세션에 저장된 id를 이용하도록 수정
  src/main/java/com/example/newsfeed/user/controller/UserController.java
  src/main/java/com/example/newsfeed/user/dto/UserRequestDto.java
  src/main/java/com/example/newsfeed/user/service/UserService.java
Labels: 수정

#68 docs: README 추가
  README.md
  img.png
Labels: 문서
